language: node_js
sudo: false
node_js:
  - 10.15.0
  
matrix:
  include:
    
    - node_js: "10"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
    
  # Update Node.js modules
  - |
    # Prune and rebuild node_modules
    if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
script:
  # Run test script
  - npm run test-ci
  # Run linting
  - npm run lint
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.10.0
    coveralls < ./coverage/lcov.info